FIND_PATH(SMF_INCLUDE_DIR SMF.h
  PATHS
  /usr/local/include
  /usr/include
  $ENV{SMFDIR}
)

FIND_LIBRARY(SMF_LIBRARY
  NAMES smf
  PATHS
  /usr/local/lib
  /usr/lib
  $ENV{SMFDIR}
)

set(SMF_FOUND "FALSE" )
if (SMF_INCLUDE_DIR AND SMF_LIBRARY)
    set(SMF_FOUND "TRUE" )
endif()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SMF DEFAULT_MSG SMF_LIBRARY SMF_INCLUDE_DIR)